### ISSUE TITLE
jssdk全局

### ISSUE THREAD

**Issue by cca313** [luchanan/vue2.0-multi-page#1]
可以配置一个入口index.html 所有的全局使用的资源都可以放在index.html

**Comment by luchanan** [comment]
@cca313 单页应用可以这样考虑；但是涉及多页面，暂时没有想到很好的办法，不过可以参考一下https://github.com/luchanan/webpack-MultiplePage

**Comment by cca313** [comment]
@luchanan  我昨天想到一个办法是在路由的钩子里把资源注册进去
