### ISSUE TITLE
关于多页面传参问题

### ISSUE THREAD

**Issue by HebutJipeng** [luchanan/vue2.0-multi-page#6]
请问，您是准备如何实现在不同页面之间的传参问题呢？ 完成例如： 点击首页的图片，跳转到对应的page 等等。 期待您的回复

**Comment by luchanan** [comment]
好问题，曾经在做angular1.x，使用router，遇到一个问题，类似这种router：/product/detail/35刷新就会报404，后来写了个服务器配置才解决。在vue多页面（在你配置了多页面的router的前提下），我在首页router：/index，点击里面的某个商品：/product/detail/35（曾在github某个项目里头看到多页面的路由之间不能相互跳转，可能原因是这个吧），这里也许需要在服务器配置一下，不过我没有实验。我这里目前并没有使用router(将来会加入，因为在移动端，列表跳到商品详情，再返回列表保持对应的数据和滚动位置，这是个很大的问题)，点击都是跳到对应的url（我觉得url不够优雅，我希望/center/index,/center/collect这种层级关系），目前我想的比较挫的方法：
1. 在你要跳转的url加上？，然后在其他页面用js来获取？的参数
2. 本地存储 
这个问题持续关注...

**Comment by HebutJipeng** [comment]
您好， 虽然我现在已经在考虑是否接着使用多页面的vue了，我还是借鉴了一下其他同学的代码
https://github.com/zhang-chuang/vue-cli-multi-page
这位同学使用的是 vux的querystring这个简单的传参应该是没有问题的
附一个 vux 的文档 https://vux.li/#/

还有关于localstorage 的问题，之前写angular的时候确实是一个解决的办法

感谢回答。

**Comment by keepmood** [comment]
你好，我在本地安装项目时遇到以下问题，可否帮忙看下。

npm install 的时候提示：
npm WARN karma-sinon-chai@1.3.1 requires a peer of sinon@^2.1.0 but none was installed.

npm run dev时报错：
![wx20170427-171647](https://cloud.githubusercontent.com/assets/6124209/25476647/665c5462-2b6d-11e7-89a2-b12169ca482f.png)

**Comment by luchanan** [comment]
@keepmood 你这个npm的依赖包可能没有全部安装成功，npm如果没有fanqiang就用淘宝源再安装一次吧（首先删除node_modules后再安装）。

**Comment by luchanan** [comment]
抛砖引玉：https://github.com/luchanan/vue_cli_multiple_page/blob/master/note/R5_%E5%A4%9A%E9%A1%B5%E9%9D%A2%E5%A4%9A%E8%B7%AF%E7%94%B1%E8%B7%B3%E8%BD%AC%E4%BB%A5%E5%8F%8A%E5%8F%82%E6%95%B0%E4%BC%A0%E9%80%92%E8%B7%B3%E8%BD%AC.md
