### ISSUE TITLE
请教如何添加 image-webpack-loader

### ISSUE THREAD

**Issue by li9269391** [luchanan/vue2.0-multi-page#9]
{
   test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
    loaders: [
        {
            loader: 'url-loader',
            query: {
                limit: 8192,
                name: utils.assetsPath('images/[name].[hash:7].[ext]')
            }
        },
        {
            loader: 'image-webpack-loader',
            query: {
                progressive: true,
                optimizationLevel: 8,
                interlaced: false,
                pngquant: {
                    quality: '70-90',
                    speed: 4
                }
            }
        }
    ]
}

以上配置会报错，或者有什么方法做图片压缩吗

**Comment by luchanan** [comment]
这个请google解决吧
